config/routes.rb
Rails.application.routes.draw do
  
   
  get 'home/index'

  devise_for :users
  
  resources :cities do
  	resources :restraunts
  end

  root 'home#index'

end

app/models/city.rb
class City < ActiveRecord::Base
  

  belongs_to :user

  has_many :restraunts
  
  mount_uploader :image, ImageUploader


end

app/models/restraunt.rb
class Restraunt < ActiveRecord::Base
  belongs_to :user

  belongs_to :city

  mount_uploader :restraunt_image, RestrauntImageUploader


end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :cities

  has_many :restraunts

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :current_password, :is_female, :date_of_birth) }
        end
  
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /cities
  def index
    @cities = City.all
  end

  # GET /cities/1
  def show
    @restraunts = Restraunt.where(city_id: @city.id)
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  def create
    @city = City.new(city_params)
    @city.user = current_user

    if @city.save
      redirect_to @city, notice: 'City was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cities/1
  def update
    if @city.update(city_params)
      redirect_to @city, notice: 'City was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cities/1
  def destroy
    @city.destroy
    redirect_to cities_url, notice: 'City was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def city_params
      params.require(:city).permit(:name, :country, :user_id, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@cities = City.all
  end
end

app/controllers/restraunts_controller.rb
class RestrauntsController < ApplicationController
  before_action :set_restraunt, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_city

  # GET /restraunts
  def index
    @restraunts = Restraunt.all
  end

  # GET /restraunts/1
  def show
  end

  # GET /restraunts/new
  def new
    @restraunt = Restraunt.new
  end

  # GET /restraunts/1/edit
  def edit
  end

  # POST /restraunts
  def create
    @restraunt = Restraunt.new(restraunt_params)
    @restraunt.user = current_user
    @restraunt.city_id = @city.id

    if @restraunt.save
      redirect_to @city, notice: 'Restraunt was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /restraunts/1
  def update
    if @restraunt.update(restraunt_params)
      redirect_to @city, notice: 'Restraunt was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /restraunts/1
  def destroy
    @restraunt.destroy
    redirect_to restraunts_url, notice: 'Restraunt was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:city_id])
    end

    def set_restraunt
      @restraunt = Restraunt.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def restraunt_params
      params.require(:restraunt).permit(:name, :about, :restraunt_image, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/restraunts_helper.rb
module RestrauntsHelper
end

app/views/cities/_form.html.erb
<%= simple_form_for(@city) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :country %>
    <%= f.input :image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing City</h1>

<%= render 'form' %>

<%= link_to 'Show', @city %> |
<%= link_to 'Back', cities_path %>

app/views/cities/index.html.erb
<div class="container">
    <div class="row" id="city_thumbnails">
        <h2 id="city_title">Cities</h2>
        <% @cities.each do |city| %>
          <div class="col-sm-6 col-md-4">
              <div class="thumbnail">
                  <a href="/cities/<%= city.id%>">
                    <img src="<%= city.image %>">
                  </a>
              </div>
          </div>
        <% end %>
    </div>




  <h1>Listing Cities</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Country</th>
          <th>User</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @cities.each do |city| %>
          <tr>
            <td><%= city.name %></td>
            <td><%= city.country %></td>
            <td><%= city.user %></td>
            <td><%= link_to 'Show', city %></td>
            <td><%= link_to 'Edit', edit_city_path(city) %></td>
            <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <%= link_to 'New City', new_city_path %>

</div>

app/views/cities/new.html.erb
<h1>New City</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path %>

app/views/cities/show.html.erb
<div class="jumbotron" id="city_jumbotron" style="background-image: url(<%= @city.image %>)">
  <h1><%= @city.name %>, <%= @city.country %></h1>
</div>

<div class="container">
	<div class="row">
		<% @restraunts.each do |restraunt| %>
		  <div class="col-sm-6 col-md-4">
			 <a href="/cities/<%= restraunt.city.id%>/restraunts/<%= restraunt.id%>">
			    <div class="thumbnail">
			      <img src="<%= restraunt.restraunt_image %>">
			      <div class="caption">
			        <h3 id="restraunt_thumnail_text"><%= restraunt.name %></h3>   
			      </div>
			    </div>
			 </a>
		  </div>
		<% end %>  
	</div>


	
	<%= link_to 'Edit', edit_city_path(@city) %> |
	<%= link_to 'Back', cities_path %>
</div>

app/views/home/index.html.erb
<div class="jumbotron" id="homepage_jumbotron">
    <h1 id="homepage_heading">Find your local kosher</h1>
    <p>Find and review kosher restraunts from cities all around the globe</p>
    <div class="btn-group">
        <button class="btn btn-default btn-lg dropdown-toggle btn btn-success" id="homepage_button" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Select City <span class="caret"></span>
        </button>
          <ul class="dropdown-menu">
              <% @cities.each do |city| %>
                <a href="cities/<%= city.id%>">
                  <li><%= city.name %>, <%= city.country %></li>
                </a>
              <% end %>
          </ul>
    </div>
</div>

<div class="container">
    <div class="row" id="city_thumbnails">
        <h2>Cities</h2  >
        <% @cities.each do |city| %>
          <div class="col-sm-6 col-md-4">
              <div class="thumbnail">
                  <a href="/cities/<%= city.id%>">
                    <img src="<%= city.image %>">
                  </a>
              </div>
          </div>
        <% end %>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">KosherFinder</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Add City", new_city_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to 'My Account', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kosherapp</title>
  <!-- BOOTSTRAP -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">	

	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
	<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
	


  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
</head>
<body>

<%= render "layouts/navbar" %>

	<%= yield %>


</body>
</html>

app/views/restraunts/_form.html.erb
<%= simple_form_for [@city, @restraunt] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :about %>
    <%= f.input :restraunt_image %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restraunts/edit.html.erb
<h1>Editing Restraunt</h1>

<%= render 'form' %>

<%= link_to 'Show', "#" %> |
<%= link_to 'Back', "#" %>

app/views/restraunts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Restraunts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>About</th>
      <th>Restraunt image</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restraunts.each do |restraunt| %>
      <tr>
        <td><%= restraunt.name %></td>
        <td><%= restraunt.about %></td>
        <td><%= restraunt.restraunt_image %></td>
        <td><%= restraunt.user %></td>
        <td><%= link_to 'Show', restraunt %></td>
        <td><%= link_to 'Edit', edit_restraunt_path(restraunt) %></td>
        <td><%= link_to 'Destroy', restraunt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restraunt', new_restraunt_path %>

app/views/restraunts/new.html.erb
<div class="container">
	<h1>New Restraunt</h1>

	<%= render 'form' %>

	<%= link_to 'Back', "#" %>
</div>	

app/views/restraunts/show.html.erb
<div class="jumbotron" id="city_jumbotron" style="background-image: url(<%= @restraunt.restraunt_image %>)">
  <h1><%= @restraunt.name %>, <%= @restraunt.city.name %></h1>
</div>




<%= link_to 'Edit', edit_city_restraunt_path %> |
<%= link_to 'Back', "#" %>